version: '2'

services:
  taiga:
    build: .
    ports:
      - 80:80
    depends_on:
      - postgres
    environment:
      TAIGA_HOSTNAME: plateforme.ic.com
      TAIGA_DB_HOST: postgres
      TAIGA_DB_NAME: taigadb
      TAIGA_DB_USER: taiga
      TAIGA_DB_PASSWORD: password
    volumes:
      - ./media:/usr/src/taiga-back/media
      - ./taiga-conf:/taiga
    networks:
      - taiga_net
  
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: taigadb
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - taiga_net

networks:
   taiga_net:
      driver: bridge      
