version: "2"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - "ES_JAVA_OPTS: -Xmx512m -Xms512m"
        volumes:
            - ${ROOT_SHARED_DATA}/elasticsearch/data:/usr/share/elasticsearch/data
        networks:
            - logstash_net
            
    kibana:
        image: docker.elastic.co/kibana/kibana:5.3.0
        ports:
            - "5601:5601"
        links:
            - elasticsearch
        environment:
            - SERVER_NAME=Kibana
            - SERVER_HOST="0"
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=changeme
            - XPACK_SECURITY_ENABLED=false
            - XPACK_MONITORING_ENABLED=false
        networks:
            - logstash_net
            
    logstash:
        #image: docker.elastic.co/logstash/logstash:5.3.0
        build: ../container_logstash
        ports:
            - "8080:8080"
            - "5000:5000"
        links:
            - elasticsearch
        networks:
            - logstash_net
            
    tomcat:
        build: ../container_tomcat_filebeat
        ports:
            - "9595:8080"
        networks:
            - logstash_net
    
networks:
    logstash_net:
        driver: bridge