version: "2"

services:
    jenkins:
        image: jenkins:latest
        ports: 
            - "8080:8080"
            - "50000:50000"
        volumes:
            - ${ROOT_DATA}/jenkins_home:/var/jenkins_home

    nexus:
        image: sonatype/nexus3
        ports:
            - "8081:8081"
        volumes:
            - ${ROOT_SHARED_DATA}/nexus:/nexus-data
     
    #nexus2:
    #    image: sonatype/nexus
    #    ports:
    #        - "8081:8081"
    #    volumes:
    #        - ${ROOT_SHARED_DATA}/nexus2:/sonatype-work
    
    db_sonar:
        image: mysql:5.7
        networks:
            - ic_net
        ports:
            - "3306:3306"
        volumes:
            - ${ROOT_SHARED_DATA}/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=@Soleil1
            - MYSQL_DATABASE=sonar
            - MYSQL_USER=sonar
            - MYSQL_PASSWORD=sonar
            
    sonarqube:
        image: sonarqube:alpine
        links:
            - db_sonar
        networks:
            - ic_net
        ports:
            - "9000:9000"
            - "9092:9092"
        environment:
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
            - SONARQUBE_JDBC_URL=jdbc:mysql://db_sonar:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
        volumes:
            #- ${ROOT_SHARED_DATA}/sonarqube/conf:/opt/sonarqube/conf
            - ${ROOT_SHARED_DATA}/sonarqube/data:/opt/sonarqube/data
            - ${ROOT_SHARED_DATA}/sonarqube/extensions:/opt/sonarqube/extensions
            #- ${ROOT_SHARED_DATA}/sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins

    db_rocket:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ${ROOT_DATA}/mongo:/data/db
        command: mongod --smallfiles

    rocket:
        image: rocket.chat:latest
        links:
            - db_rocket
        ports:
            - "80:3000"
        volumes:
            - ${ROOT_SHARED_DATA}/rocket.chat/uploads:/app/uploads
        environment:
            - PORT=3000
            - MONGO_URL=mongodb://db_rocket:27017/rocketchat
            
    mantis:
        image: chessmasterrr/mantis:latest
        links:
            - db_sonar
        networks:
            - ic_net
        ports:
            - "5000:80"
        volumes:
            - ${ROOT_SHARED_DATA}/mantis/main:/var/www/html/config

networks:
    ic_net:
        driver: bridge
