version: "3"

services:
    web:
        build: ../apache/
        image: apave-httpd:1.0
        container_name: apave-httpd
        ports:
            - "95:80"
        networks:
            - my-network

    tomcat:
        build: ../tomcat/
        image: apave-tomcat:1.0
        container_name: apave-tomcat
        volumes:
            - /C/docker_data/tomcat_personal_conf:/usr/local/tomcat/personal_conf
        ports:
            - "9595:8080"
        networks:
            - my-network

    db:
        image: mariadb
        container_name: apave-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: apave_test
            MYSQL_USER: apave
            MYSQL_PASSWORD: apave
        ports:
            - "3306:3306"
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
