FROM tomcat:latest
MAINTAINER Thomas Bonavia <thomas.bonavia@apave.com>

# RUN curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.3.0-amd64.deb
# RUN dpkg -i filebeat-5.3.0-amd64.deb

